---
# Dataset Config File

name: TrnavaZilina
path: "../../datasets/TrnavaZilina/main"

# Camera PTZ limits and default values
camera_params:
  lens_fov_horiz_deg: 115
  pitch_tilt_deg: -15 # pitch rotation correction
  pan_deg:
    default: 24.7
    min: -24.3
    max: 29.7
  tilt_deg:
    default: -0.6
    min: -2
    max: 5
  zoom_f:
    default: 67
    min: 40
    max: 70

# An array of cameras for frame splitting due to detection.
# Note: You can also use more than 3 cameras.
frame_splitter_params:
- pan_deg: -24.7
  tilt_deg: -2.9
  zoom_f: 82
- pan_deg: 1.7
  tilt_deg: -0.79
  zoom_f: 69
- pan_deg: 29.3
  tilt_deg: 1.7
  zoom_f: 71.5

# Coordinates of pitch corners.
# Note: You can nest it under p0 (1. period) and p1 (2. period) as:
#  pitch_corners:
#    p0:
#      left bottom:
#      ...
#     p1:
#      left bottom:
#      ...
pitch_corners:
  p0: # first period
    left bottom:
      x: 406
      y: 1117
    left top:
      x: 1423
      y: 821
    right top:
      x: 2619
      y: 880
    right bottom:
      x: 3710
      y: 1508
  p1: # second period
    left bottom:
      x: 404
      y: 1114
    left top:
      x: 1419
      y: 815
    right top:
      x: 2616
      y: 871
    right bottom:
      x: 3706
      y: 1499

# Margins in pixels of the pitch sides
# to hide distractions for the detector.
mask_margins:
  top: -10
  right: 30
  bottom: -30
  left: -25

# A list of bounding boxes.
# If a detection lies inside of any of them, it gets discarded.
detection_blacklist:
  - - 1778 # x1 # lens flare
    - 1155 # y1
    - 1828 # x2
    - 1225 # y2
  - - 1819 # lens flare
    - 1094
    - 1880
    - 1142