---
# -----------------------------------------------------------------------------
# Debug
debug:
  show_split_frames: false
  show_top_down_window: false
  show_warped_frame: false
  draw_grid: false
  draw_detections: true
  draw_roi: true
  draw_players_bb: true
  print_camera_stats: false
  ignore_bounds: false

print_profiler_stats: true
show_original: true

# -----------------------------------------------------------------------------
# Dataset
dataset:
  config: "./configs/config_trnava_zilina.yaml"
  video: "p0_zoom.mp4"
  # video: "main_p0.mp4"

correct_rotation: true

# -----------------------------------------------------------------------------
# Evaluation
eval:
  export_every_x_seconds: 10
  pitch_overlay: false

# -----------------------------------------------------------------------------
# Detection
detector:
  enabled: true
  filter_detections: true
  ball_confidence: 0.35
  ball_max_det: 1
  players_confidence: 0.25

# -----------------------------------------------------------------------------
# Filters
ball_pf:
  dt: 0.1
  N: 500 # Number of particles

  # Uncertainty of predictions.
  # - Determines the receptive field of the filter.
  # - Controls the rate at which the variance 
  #   of the particle filter increases.
  std_pos: 10

  # Uncertainty of measurements
  # - Determines the size of the blob around the measurement.
  # - Controls the filter sensitivity on measurements
  #   (the higher, the less sensitive).
  std_meas: 150
  
  # How to position the particle filter 
  # between the players’ center and the ball.
  players_ball_alpha: 0.6 

players_kf:
  dt: 0.1
  std_acc: 1 # Standard deviation of acceleration (KF prediction).
  std_meas: 5 # Standard deviation of measurements.

u_control: # PF control input
  center:
    # Weight of gravitating towards the players’ center.
    alpha: 0.1

    # Variance threshold at which the camera starts 
    # moving towards the players’ center.
    var_th: 5000
  velocity:
    # Weight of panning the camera with the mean players' velocity vector.
    alpha: 2

pid:
  x:
    kp: 0.03
    ki: 0.009
    kd: 0
  y:
    kp: 0.03
    ki: 0.009
    kd: 0
  f:
    kp: 0.01
    ki: 0
    kd: 0

# Particle filter variance zoom limits.
# Maps the PF variance to the camera zoom limits.
zoom:
  var_min: 100
  var_max: 5000

  # Zoom based on the players' bounding box.
  bb:
    margin_px: 300 # Margin around the player's bounding box.

# -----------------------------------------------------------------------------
# Dead zone
dead_zone:
  enabled: false
  size:
  - 80
  - 300