---
name: TrnavaZilina
path: "../../datasets/TrnavaZilina/main"

camera_params:
  lens_fov_horiz_deg: 115
  pan_deg:
    default: 0.3
    min: -27
    max: 32
  tilt_deg:
    default: -1.8
    min: -2
    max: 4
  zoom_f:
    default: 40
    min: 40
    max: 80

frame_splitter_params:
- pan_deg: -20.8
  tilt_deg: -1.8
  zoom_f: 93.5
- pan_deg: 1.7
  tilt_deg: -0.39
  zoom_f: 84
- pan_deg: 25.2
  tilt_deg: 1.1
  zoom_f: 84.5

pitch_coords:
  p0:
    left bottom:
      x: 406
      y: 1117
    left top:
      x: 1423
      y: 821
    right top:
      x: 2619
      y: 880
    right bottom:
      x: 3710
      y: 1508
  p1:
    left bottom:
      x: 404
      y: 1114
    left top:
      x: 1419
      y: 815
    right top:
      x: 2616
      y: 871
    right bottom:
      x: 3706
      y: 1499

mask_margins:
  top: -10
  right: 40
  bottom: -30
  left: -40

detection_blacklist:
  - - 1778 # x1 # lens flare
    - 1155 # y1
    - 1828 # x2
    - 1225 # y2
  - - 1819 # lens flare
    - 1094
    - 1880
    - 1142