---
# Dataset Config File

name: SoccerTrack
path: "../../datasets/SoccerTrack/wide_view/videos"

# Camera PTZ limits and default values
camera_params: 
  pan_deg:
    default: 12
    min: -60
    max: 60
  tilt_deg:
    default: 9
    min: 5
    max: 12
  zoom_f:
    default: 120
    min: 90
    max: 200

# An array of cameras for frame splitting due to detection.
# Note: You can also use more than 3 cameras.
frame_splitter_params:
- pan_deg: -30
  tilt_deg: 9
  zoom_f: 1003
- pan_deg: 9
  tilt_deg: 9
  zoom_f: 220
- pan_deg: 40
  tilt_deg: 9
  zoom_f: 220

# Coordinates of pitch corners.
# Note: You can nest it under p0 (1. period) and p1 (2. period) as:
#  pitch_corners:
#    p0:
#      left bottom:
#      ...
#     p1:
#      left bottom:
#      ...
pitch_corners:
  left bottom:
    x: 109
    y: 885
  left top:
    x: 2934
    y: 484
  right top:
    x: 4121
    y: 503
  right bottom:
    x: 6211
    y: 882
