---
# -----------------------------------------------------------------------------
# Debug
debug:
  # Frame splitter
  show_split_frames: false # Show the FrameSplitter frames with detections.
  show_frame_mask: false # Mask out everything outside of the pitch.

  # Camera
  draw_grid: false # Visualize the point grid of the used projection scheme.
  draw_roi: true # Draw the regions-of-interest of cameras.
  print_camera_stats: false # Print the camera state (PTZ, PID, FoV).
  ignore_bounds: false # Ignore the PTZ limits defined in the dataset config file.
  mouse_use_pid: false # Use PID in mouse mode. Otherwise uses free camera.
  
  # Detection
  draw_detections: true # Draw player and ball bounding boxes.
  draw_players_bb: true # Draw the players' bounding box.
  
  # Top Down
  show_warped_frame: false # Show the original pitch in top-down view. 
  draw_top_down_players_center: true

print_profiler_stats: true
show_original: true
show_top_down_window: false # Show the top-down pitch model with marked players.

# -----------------------------------------------------------------------------
# Dataset
dataset:
  config: "./configs/config_trnava_zilina.yaml"
  # video: "p1_goal1.mp4"
  video: "main_p0.mp4"

correct_rotation: true

# -----------------------------------------------------------------------------
# Evaluation
eval:
  export_every_x_seconds: 10 # Time interval to export a warped frame.
  pitch_overlay: false # Overlay the pitch model scheme on the exported frame.

# -----------------------------------------------------------------------------
# Detection
detector:
  enabled: true
  
  # Filter detections based on `detection_blacklist` in dataset config file.
  filter_detections: true 
  
  # Parameters for the general detector
  conf: 0.2 # confidence threshold
  
  # Parameters for the ball detector
  ball:
    enabled: true # Whether to use a separate ball detector.
    conf: 0.3
    max_det: 10 # Maximum number of detections for the ball.

# -----------------------------------------------------------------------------
# Filters
ball_pf:
  dt: 0.1
  N: 500 # Number of particles

  # Uncertainty of predictions.
  # - Determines the receptive field of the filter.
  # - Controls the rate at which the variance 
  #   of the particle filter increases.
  std_pos: 10

  # Uncertainty of measurements
  # - Determines the size of the blob around the measurement.
  # - Controls the filter sensitivity on measurements
  #   (the higher, the less sensitive).
  std_meas: 150
  
  # How to position the particle filter 
  # between the players’ center and the ball.
  players_ball_alpha: 0.6 

players_kf:
  dt: 0.1
  std_acc: 1 # Standard deviation of acceleration (KF prediction).
  std_meas: 5 # Standard deviation of measurements.

u_control: # PF control input
  center:
    # Weight of gravitating towards the players’ center.
    alpha: 0.1

    # Variance threshold at which the camera starts 
    # moving towards the players’ center.
    var_th: 5000
    
  velocity:
    # Weight of panning the camera with the mean players' velocity vector.
    alpha: 2

pid:
  x:
    kp: 0.03
    ki: 0.009
    kd: 0
  y:
    kp: 0.03
    ki: 0.009
    kd: 0
  f:
    kp: 0.01
    ki: 0
    kd: 0

# Particle filter variance zoom limits.
# Maps the PF variance to the camera zoom limits.
zoom:
  var_min: 100
  var_max: 5000

  # Zoom based on the players' bounding box.
  bb:
    margin_px: 350 # Margin around the player's bounding box.


# -----------------------------------------------------------------------------
# Evaluation
evaluation:
  image_size:
    - 1280
    - 720
  